
export const online = [
  {
    id: 1,
    cover: "../images/o1.png",
    hoverCover: "../images/o1.1.png",
    backgroundImage:"../images/ll2.jpg",
    courseName: "UI/UX Design",
    course: "25 Cours",
    description: "Apprenez à concevoir des interfaces utilisateurs modernes, avec une approche UX centrée sur l'utilisateur.",
    formateur: "Jean Dupont",
    duration: "3 mois",
    price: "300 €",
  },
  {
    id: 2,
    cover: "../images/o2.png",
    hoverCover: "../images/o2.1.png",
    backgroundImage:"../images/xx.avif",
    courseName: "Art & Design",
    course: "25 Cours",
    description: "Explorez les fondamentaux de l'art et du design pour stimuler votre créativité dans divers projets visuels.",
    formateur: "Pauline Leroy",
    duration: "2 mois",
    price: "250 €",
  },
  {
    id: 3,
    cover: "../images/o8.png",
    hoverCover: "../images/o8.1.png",
    backgroundImage:"../images/ss.jpg",
    courseName: "Marketing",
    course: "30 Cours",
    description: "Maîtrisez les bases du marketing digital, des réseaux sociaux à la stratégie d'acquisition.",
    formateur: "Rachid Ben Ali",
    duration: "2 mois",
    price: "200 €",
  },
  {
    id: 4,
    cover: "../images/o9.png",
    hoverCover: "../images/o9.1.png",
     backgroundImage:"../images/ii.png",
    courseName: "Graphic Design",
    course: "80 Cours",
    description: "Formation approfondie en design graphique : Photoshop, Illustrator, typographie, mise en page et plus.",
    formateur: "Julie Martin",
    duration: "4 mois",
    price: "350 €",
  },
  {
    id: 5,
    cover: "../images/o11.png",
    hoverCover: "../images/o11.1.png",
    backgroundImage:"../images/dd.jpg",
    courseName: "Business Administration",
    course: "17 Cours",
    description: "Comprendre les principes fondamentaux de la gestion d'entreprise : finance, RH, management.",
    formateur: "Karim Haddad",
    duration: "3 mois",
    price: "400 €",
  },
  {
    id: 6,
    cover: "../images/o12.png",
    hoverCover: "../images/o12.1.png",
    courseName: "Web Management",
    course: "17 Cours",
    description: "Apprenez à gérer et à optimiser des projets web de A à Z : gestion d'équipe, SEO, outils numériques.",
    formateur: "Sonia Mezghani",
    duration: "3 mois",
    price: "300 €",
  },
]



